### ISSUE TITLE
Creation of user service

### ISSUE THREAD

**Issue by Satwik-Bhardwaj** [Satwik-Bhardwaj/Mithril-ChatApp#1]
Please create a basic user service for the application. It will use spring boot and it should involve endpoints to create a user, delete the user, and get user details. It will use PostgreSQL to store the user information. 

Also, configure the application `spring.jpa.hibernate.ddl-auto=update` so the table can be automatically created and updated.
The table structure should be the same as given in the documentation.

Please create BaseEntity which is extended by the User Entity. 
BaseEntity should have the following fields:
1. Id (UUID)
2. createdAt (LocalDateTime)
3. updatedAt (LocalDateTime)
4. createdBy (String)
5. updatedBy (String)
6. status (Enum [ACTIVE, INACTIVE and DELETED)

Please refer to the schema here:
https://whimsical.com/mithiril-chatapp-dbms-ByzAEQh5SYR16i5gsYdcg8

Please check the documentation for more details, and feel free to ask anything.

**Note**: You don't need to add any security.

**Comment by Naresh-Kushwaha** [comment]
Hi @Satwik-Bhardwaj, I'm intersterested in working on this issue. Could you please assign it to me?

**Comment by Satwik-Bhardwaj** [comment]
> Hi @Satwik-Bhardwaj, I'm intersterested in working on this issue. Could you please assign it to me?

@Naresh-Kushwaha I'm happy to hear that you are interested in my project and want to make some contribution. I am assigning this issue to you. Please proceed. I hope you will code it properly. However, I am updating the description of this issue to learn more about it.

**Comment by Naresh-Kushwaha** [comment]
Hi @Satwik-Bhardwaj , Please tell me from where should I learn Spring framework.any course?
